// <auto-generated />
using LocalInformationSystem.Data.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocalInformationSystem.Data.Migrations
{
    [DbContext(typeof(BgDatabaseContext))]
    [Migration("20260927091558_AddedIsDeletedPropertyToParkAndLandmarkEntities")]
    partial class AddedIsDeletedPropertyToParkAndLandmarkEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LocalInformationSystem.Data.Entities.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CityID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<int?>("ElevationMeters")
                        .HasColumnType("int");

                    b.Property<bool?>("IsCapital")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Population")
                        .HasColumnType("int");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int")
                        .HasColumnName("ProvinceID");

                    b.HasKey("CityId")
                        .HasName("PK__Cities__F2D21A965B5FE817");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("LocalInformationSystem.Data.Entities.HistoricalEvent", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EventID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("EventId")
                        .HasName("PK__Historic__7944C87027AFE9F5");

                    b.ToTable("HistoricalEvents");
                });

            modelBuilder.Entity("LocalInformationSystem.Data.Entities.Landmark", b =>
                {
                    b.Property<int>("LandmarkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LandmarkID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LandmarkId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("CityID");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool?>("UnescoSite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("LandmarkId")
                        .HasName("PK__Landmark__3195B57F7409FDD7");

                    b.HasIndex("CityId");

                    b.ToTable("Landmarks");
                });

            modelBuilder.Entity("LocalInformationSystem.Data.Entities.Mountain", b =>
                {
                    b.Property<int>("MountainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MountainID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MountainId"));

                    b.Property<decimal?>("AreaSqKm")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("ElevationMeters")
                        .HasColumnType("int");

                    b.Property<string>("HighestPeak")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MountainId")
                        .HasName("PK__Mountain__268FB26D2178BB2F");

                    b.ToTable("Mountains");
                });

            modelBuilder.Entity("LocalInformationSystem.Data.Entities.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ParkID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParkId"));

                    b.Property<decimal>("AreaSqKm")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("EstablishedYear")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("MountainId")
                        .HasColumnType("int")
                        .HasColumnName("MountainID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("UnescoSite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("ParkId")
                        .HasName("PK__Parks__7D67D36C69D85A03");

                    b.HasIndex("MountainId");

                    b.ToTable("Parks");
                });

            modelBuilder.Entity("LocalInformationSystem.Data.Entities.Province", b =>
                {
                    b.Property<int>("ProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProvinceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProvinceId"));

                    b.Property<string>("AdministrativeCenter")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("AreaSqKm")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Population")
                        .HasColumnType("int");

                    b.HasKey("ProvinceId")
                        .HasName("PK__Province__FD0A6FA3FB7A9662");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("LocalInformationSystem.Data.Entities.River", b =>
                {
                    b.Property<int>("RiverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RiverID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RiverId"));

                    b.Property<decimal>("LengthKm")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Outflow")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RiverId")
                        .HasName("PK__Rivers__54DB03CB67C09060");

                    b.ToTable("Rivers");
                });

            modelBuilder.Entity("LocalInformationSystem.Data.Entities.City", b =>
                {
                    b.HasOne("LocalInformationSystem.Data.Entities.Province", "Province")
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceId")
                        .IsRequired()
                        .HasConstraintName("FK__Cities__Province__72C60C4A");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("LocalInformationSystem.Data.Entities.Landmark", b =>
                {
                    b.HasOne("LocalInformationSystem.Data.Entities.City", "City")
                        .WithMany("Landmarks")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK__Landmarks__CityI__76969D2E");

                    b.Navigation("City");
                });

            modelBuilder.Entity("LocalInformationSystem.Data.Entities.Park", b =>
                {
                    b.HasOne("LocalInformationSystem.Data.Entities.Mountain", "Mountain")
                        .WithMany("Parks")
                        .HasForeignKey("MountainId")
                        .HasConstraintName("FK__Parks__MountainI__00200768");

                    b.Navigation("Mountain");
                });

            modelBuilder.Entity("LocalInformationSystem.Data.Entities.City", b =>
                {
                    b.Navigation("Landmarks");
                });

            modelBuilder.Entity("LocalInformationSystem.Data.Entities.Mountain", b =>
                {
                    b.Navigation("Parks");
                });

            modelBuilder.Entity("LocalInformationSystem.Data.Entities.Province", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
