// <auto-generated />
using LocalInformationSystem.Data.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocalInformationSystem.Data.Migrations
{
    [DbContext(typeof(BgDatabaseContext))]
    [Migration("20261003213743_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LocalInformationSystem.Data.Entities.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CityID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<int?>("ElevationMeters")
                        .HasColumnType("int");

                    b.Property<bool?>("IsCapital")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Population")
                        .HasColumnType("int");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int")
                        .HasColumnName("ProvinceID");

                    b.HasKey("CityId")
                        .HasName("PK__Cities__F2D21A965B5FE817");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            ElevationMeters = 550,
                            IsCapital = true,
                            Name = "Sofia",
                            Population = 1241000,
                            ProvinceId = 1
                        },
                        new
                        {
                            CityId = 2,
                            ElevationMeters = 164,
                            IsCapital = false,
                            Name = "Plovdiv",
                            Population = 345000,
                            ProvinceId = 2
                        },
                        new
                        {
                            CityId = 3,
                            ElevationMeters = 20,
                            IsCapital = false,
                            Name = "Varna",
                            Population = 335000,
                            ProvinceId = 3
                        },
                        new
                        {
                            CityId = 4,
                            ElevationMeters = 15,
                            IsCapital = false,
                            Name = "Burgas",
                            Population = 200000,
                            ProvinceId = 4
                        },
                        new
                        {
                            CityId = 5,
                            ElevationMeters = 220,
                            IsCapital = false,
                            Name = "Veliko Tarnovo",
                            Population = 70000,
                            ProvinceId = 5
                        },
                        new
                        {
                            CityId = 6,
                            ElevationMeters = 350,
                            IsCapital = false,
                            Name = "Blagoevgrad",
                            Population = 85000,
                            ProvinceId = 6
                        },
                        new
                        {
                            CityId = 7,
                            ElevationMeters = 45,
                            IsCapital = false,
                            Name = "Ruse",
                            Population = 150000,
                            ProvinceId = 7
                        },
                        new
                        {
                            CityId = 8,
                            ElevationMeters = 120,
                            IsCapital = false,
                            Name = "Pleven",
                            Population = 100000,
                            ProvinceId = 8
                        },
                        new
                        {
                            CityId = 9,
                            ElevationMeters = 1000,
                            IsCapital = false,
                            Name = "Smolyan",
                            Population = 30000,
                            ProvinceId = 6
                        },
                        new
                        {
                            CityId = 10,
                            ElevationMeters = 150,
                            IsCapital = false,
                            Name = "Dobrich",
                            Population = 80000,
                            ProvinceId = 3
                        },
                        new
                        {
                            CityId = 11,
                            ElevationMeters = 170,
                            IsCapital = false,
                            Name = "Stara Zagora",
                            Population = 140000,
                            ProvinceId = 2
                        },
                        new
                        {
                            CityId = 12,
                            ElevationMeters = 410,
                            IsCapital = false,
                            Name = "Blagoevgrad Town",
                            Population = 45000,
                            ProvinceId = 6
                        });
                });

            modelBuilder.Entity("LocalInformationSystem.Data.Entities.HistoricalEvent", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EventID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("EventId")
                        .HasName("PK__Historic__7944C87027AFE9F5");

                    b.ToTable("HistoricalEvents");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            Description = "Establishment of the Bulgarian state under Khan Asparuh.",
                            EventYear = 681,
                            Title = "Founding of the First Bulgarian State"
                        },
                        new
                        {
                            EventId = 2,
                            Description = "Treaty of San Stefano and subsequent Congress of Berlin.",
                            EventYear = 1878,
                            Title = "Liberation of Bulgaria"
                        },
                        new
                        {
                            EventId = 3,
                            Description = "Simeon I crowned Emperor (Tsar) of the Bulgarians.",
                            EventYear = 927,
                            Title = "Coronation of Simeon I"
                        },
                        new
                        {
                            EventId = 4,
                            Description = "Bulgaria falls under Ottoman rule after the Battle of Nicopolis.",
                            EventYear = 1396,
                            Title = "Ottoman Conquest"
                        },
                        new
                        {
                            EventId = 5,
                            Description = "Major uprising against Ottoman rule leading to international attention.",
                            EventYear = 1876,
                            Title = "April Uprising"
                        },
                        new
                        {
                            EventId = 6,
                            Description = "Political changes and establishment of the People's Republic of Bulgaria.",
                            EventYear = 1944,
                            Title = "End of WWII in Bulgaria"
                        },
                        new
                        {
                            EventId = 7,
                            Description = "Transition to a multi-party democratic system and market economy reforms.",
                            EventYear = 1990,
                            Title = "Democratic Transition"
                        },
                        new
                        {
                            EventId = 8,
                            Description = "Early formation of Bulgarian tribal unions in the Balkans.",
                            EventYear = 681,
                            Title = "Establishment of Early Bulgarian Settlements"
                        });
                });

            modelBuilder.Entity("LocalInformationSystem.Data.Entities.Landmark", b =>
                {
                    b.Property<int>("LandmarkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LandmarkID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LandmarkId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("CityID");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool?>("UnescoSite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("LandmarkId")
                        .HasName("PK__Landmark__3195B57F7409FDD7");

                    b.HasIndex("CityId");

                    b.ToTable("Landmarks");

                    b.HasData(
                        new
                        {
                            LandmarkId = 1,
                            Category = "Religious",
                            CityId = 1,
                            IsDeleted = false,
                            Name = "Alexander Nevsky Cathedral",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 2,
                            Category = "Historic",
                            CityId = 2,
                            IsDeleted = false,
                            Name = "Ancient Theatre of Philippopolis",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 3,
                            Category = "Museum",
                            CityId = 3,
                            IsDeleted = false,
                            Name = "Pottery of Varna",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 4,
                            Category = "Park",
                            CityId = 3,
                            IsDeleted = false,
                            Name = "Sea Garden",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 5,
                            Category = "Historic",
                            CityId = 4,
                            IsDeleted = false,
                            Name = "Aquae Calidae",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 6,
                            Category = "Historic",
                            CityId = 5,
                            IsDeleted = false,
                            Name = "Tsarevets Fortress",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 7,
                            Category = "Historic",
                            CityId = 6,
                            IsDeleted = false,
                            Name = "Bansko Old Town",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 8,
                            Category = "Museum",
                            CityId = 7,
                            IsDeleted = false,
                            Name = "Ruse Regional History Museum",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 9,
                            Category = "Museum",
                            CityId = 8,
                            IsDeleted = false,
                            Name = "Pleven Panorama",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 10,
                            Category = "Recreation",
                            CityId = 6,
                            IsDeleted = false,
                            Name = "Pirin Mountain Hut",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 11,
                            Category = "Historic",
                            CityId = 11,
                            IsDeleted = false,
                            Name = "Stara Zagora Roman Forum",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 12,
                            Category = "Nature",
                            CityId = 9,
                            IsDeleted = false,
                            Name = "Smolyan Lakes",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 13,
                            Category = "Museum",
                            CityId = 3,
                            IsDeleted = false,
                            Name = "Varna Archaeological Museum",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 14,
                            Category = "Religious",
                            CityId = 3,
                            IsDeleted = false,
                            Name = "Varna Cathedral",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 15,
                            Category = "Park",
                            CityId = 4,
                            IsDeleted = false,
                            Name = "Burgas Sea Garden",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 16,
                            Category = "Museum",
                            CityId = 4,
                            IsDeleted = false,
                            Name = "Burgas Archaeological Museum",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 17,
                            Category = "Religious",
                            CityId = 1,
                            IsDeleted = false,
                            Name = "Rila Monastery",
                            UnescoSite = true
                        },
                        new
                        {
                            LandmarkId = 18,
                            Category = "Recreation",
                            CityId = 6,
                            IsDeleted = false,
                            Name = "Bansko Ski Area",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 19,
                            Category = "Nature",
                            CityId = 6,
                            IsDeleted = false,
                            Name = "Melnik Pyramids",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 20,
                            Category = "Spa",
                            CityId = 9,
                            IsDeleted = false,
                            Name = "Devin Mineral Baths",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 21,
                            Category = "Historic",
                            CityId = 11,
                            IsDeleted = false,
                            Name = "Shipka Memorial Church",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 22,
                            Category = "Historic",
                            CityId = 11,
                            IsDeleted = false,
                            Name = "Kazanlak Thracian Tomb",
                            UnescoSite = true
                        },
                        new
                        {
                            LandmarkId = 23,
                            Category = "Historic",
                            CityId = 8,
                            IsDeleted = false,
                            Name = "Sveshtari Tomb",
                            UnescoSite = true
                        },
                        new
                        {
                            LandmarkId = 24,
                            Category = "Museum",
                            CityId = 1,
                            IsDeleted = false,
                            Name = "Bulgaria National Museum of History",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 25,
                            Category = "Square",
                            CityId = 2,
                            IsDeleted = false,
                            Name = "Alexander of Battenberg Square",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 26,
                            Category = "Historic",
                            CityId = 2,
                            IsDeleted = false,
                            Name = "Roman Stadium of Plovdiv",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 27,
                            Category = "Historic",
                            CityId = 3,
                            IsDeleted = false,
                            Name = "Aladzha Monastery",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 28,
                            Category = "Sport",
                            CityId = 3,
                            IsDeleted = false,
                            Name = "Ticha Stadium",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 29,
                            Category = "Historic",
                            CityId = 4,
                            IsDeleted = false,
                            Name = "Aheloy Historical Site",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 30,
                            Category = "Historic",
                            CityId = 4,
                            IsDeleted = false,
                            Name = "Tsarevo Old Harbor",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 31,
                            Category = "Historic",
                            CityId = 5,
                            IsDeleted = false,
                            Name = "Veliko Tarnovo Old Town",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 32,
                            Category = "Museum",
                            CityId = 2,
                            IsDeleted = false,
                            Name = "Archeological Complex of Plovdiv",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 33,
                            Category = "Historic",
                            CityId = 7,
                            IsDeleted = false,
                            Name = "Ruse Roman Bridge Remains",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 34,
                            Category = "Religious",
                            CityId = 8,
                            IsDeleted = false,
                            Name = "Pleven St. Cyril and Methodius Church",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 35,
                            Category = "Historic",
                            CityId = 11,
                            IsDeleted = false,
                            Name = "Koprivshtitsa Historic Area",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 36,
                            Category = "Historic",
                            CityId = 7,
                            IsDeleted = false,
                            Name = "Belogradchik Fortress",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 37,
                            Category = "Nature",
                            CityId = 1,
                            IsDeleted = false,
                            Name = "Bistritsa Waterfall",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 38,
                            Category = "Museum",
                            CityId = 8,
                            IsDeleted = false,
                            Name = "Pleven Historical Museum",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 39,
                            Category = "Museum",
                            CityId = 11,
                            IsDeleted = false,
                            Name = "Etar Architectural-Ethnographic Complex",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 40,
                            Category = "Religious",
                            CityId = 6,
                            IsDeleted = false,
                            Name = "Rozhen Monastery",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 41,
                            Category = "Natural",
                            CityId = 9,
                            IsDeleted = false,
                            Name = "Devil's Throat Cave",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 42,
                            Category = "Nature",
                            CityId = 3,
                            IsDeleted = false,
                            Name = "Cape Kaliakra",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 43,
                            Category = "Historic",
                            CityId = 7,
                            IsDeleted = false,
                            Name = "Madara Rider",
                            UnescoSite = true
                        },
                        new
                        {
                            LandmarkId = 44,
                            Category = "Historic",
                            CityId = 6,
                            IsDeleted = false,
                            Name = "Perperikon",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 45,
                            Category = "Historic",
                            CityId = 3,
                            IsDeleted = false,
                            Name = "Ahtopol Old Quarter",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 46,
                            Category = "Historic",
                            CityId = 3,
                            IsDeleted = false,
                            Name = "Old Nessebar",
                            UnescoSite = true
                        },
                        new
                        {
                            LandmarkId = 47,
                            Category = "Historic",
                            CityId = 3,
                            IsDeleted = false,
                            Name = "Kaliakra Fortress",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 48,
                            Category = "Geological",
                            CityId = 4,
                            IsDeleted = false,
                            Name = "Pobiti Kamani Site",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 49,
                            Category = "Religious",
                            CityId = 2,
                            IsDeleted = false,
                            Name = "Bachkovo Monastery",
                            UnescoSite = false
                        },
                        new
                        {
                            LandmarkId = 50,
                            Category = "Culture",
                            CityId = 1,
                            IsDeleted = false,
                            Name = "National Palace of Culture",
                            UnescoSite = false
                        });
                });

            modelBuilder.Entity("LocalInformationSystem.Data.Entities.Mountain", b =>
                {
                    b.Property<int>("MountainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MountainID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MountainId"));

                    b.Property<decimal?>("AreaSqKm")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("ElevationMeters")
                        .HasColumnType("int");

                    b.Property<string>("HighestPeak")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MountainId")
                        .HasName("PK__Mountain__268FB26D2178BB2F");

                    b.ToTable("Mountains");

                    b.HasData(
                        new
                        {
                            MountainId = 1,
                            AreaSqKm = 2500.00m,
                            ElevationMeters = 2925,
                            HighestPeak = "Musala",
                            Name = "Rila"
                        },
                        new
                        {
                            MountainId = 2,
                            AreaSqKm = 1450.00m,
                            ElevationMeters = 2914,
                            HighestPeak = "Vihren",
                            Name = "Pirin"
                        },
                        new
                        {
                            MountainId = 3,
                            AreaSqKm = 6000.00m,
                            ElevationMeters = 2376,
                            HighestPeak = "Botev",
                            Name = "Stara Planina"
                        },
                        new
                        {
                            MountainId = 4,
                            AreaSqKm = 3800.00m,
                            ElevationMeters = 2191,
                            HighestPeak = "Golyam Perelik",
                            Name = "Rhodope"
                        },
                        new
                        {
                            MountainId = 5,
                            AreaSqKm = 266.00m,
                            ElevationMeters = 2290,
                            HighestPeak = "Cherni Vrah",
                            Name = "Vitosha"
                        });
                });

            modelBuilder.Entity("LocalInformationSystem.Data.Entities.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ParkID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParkId"));

                    b.Property<decimal>("AreaSqKm")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("EstablishedYear")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("MountainId")
                        .HasColumnType("int")
                        .HasColumnName("MountainID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("UnescoSite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("ParkId")
                        .HasName("PK__Parks__7D67D36C69D85A03");

                    b.HasIndex("MountainId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            AreaSqKm = 810.50m,
                            EstablishedYear = 1992,
                            IsDeleted = false,
                            MountainId = 1,
                            Name = "Rila National Park",
                            Type = "National",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 2,
                            AreaSqKm = 400.75m,
                            EstablishedYear = 1962,
                            IsDeleted = false,
                            MountainId = 2,
                            Name = "Pirin National Park",
                            Type = "National",
                            UnescoSite = true
                        },
                        new
                        {
                            ParkId = 3,
                            AreaSqKm = 716.00m,
                            EstablishedYear = 1991,
                            IsDeleted = false,
                            MountainId = 3,
                            Name = "Central Balkan National Park",
                            Type = "National",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 4,
                            AreaSqKm = 2000.00m,
                            EstablishedYear = 1985,
                            IsDeleted = false,
                            MountainId = 4,
                            Name = "Rhodope Nature Park",
                            Type = "Nature",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 5,
                            AreaSqKm = 265.00m,
                            EstablishedYear = 1934,
                            IsDeleted = false,
                            MountainId = 5,
                            Name = "Vitosha Nature Park",
                            Type = "Nature",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 6,
                            AreaSqKm = 1161.00m,
                            EstablishedYear = 1995,
                            IsDeleted = false,
                            Name = "Strandzha Nature Park",
                            Type = "Nature",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 7,
                            AreaSqKm = 500.00m,
                            EstablishedYear = 2000,
                            IsDeleted = false,
                            Name = "Bulgaria Coastal Park",
                            Type = "Coastal",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 8,
                            AreaSqKm = 120.00m,
                            EstablishedYear = 1975,
                            IsDeleted = false,
                            MountainId = 5,
                            Name = "Iskar Gorge Park",
                            Type = "Regional",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 9,
                            AreaSqKm = 500.00m,
                            EstablishedYear = 1980,
                            IsDeleted = false,
                            MountainId = 3,
                            Name = "Vrachanski Balkan Nature Park",
                            Type = "Nature",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 10,
                            AreaSqKm = 340.00m,
                            EstablishedYear = 1979,
                            IsDeleted = false,
                            Name = "Rusenski Lom Nature Park",
                            Type = "Nature",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 11,
                            AreaSqKm = 210.00m,
                            EstablishedYear = 1999,
                            IsDeleted = false,
                            Name = "Belasitsa Nature Park",
                            Type = "Nature",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 12,
                            AreaSqKm = 450.00m,
                            EstablishedYear = 1988,
                            IsDeleted = false,
                            MountainId = 4,
                            Name = "Osogovo Mountain Park",
                            Type = "Mountain",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 13,
                            AreaSqKm = 75.00m,
                            EstablishedYear = 1962,
                            IsDeleted = false,
                            MountainId = 5,
                            Name = "Sinite Kamani Reserve",
                            Type = "Reserve",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 14,
                            AreaSqKm = 600.00m,
                            EstablishedYear = 1990,
                            IsDeleted = false,
                            MountainId = 3,
                            Name = "Sredna Gora Park",
                            Type = "Regional",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 15,
                            AreaSqKm = 350.00m,
                            EstablishedYear = 2001,
                            IsDeleted = false,
                            Name = "Strandzha Coastal Park",
                            Type = "Coastal",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 16,
                            AreaSqKm = 150.00m,
                            EstablishedYear = 1985,
                            IsDeleted = false,
                            Name = "Persina Nature Park",
                            Type = "Nature",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 17,
                            AreaSqKm = 48.00m,
                            EstablishedYear = 1940,
                            IsDeleted = false,
                            Name = "Ropotamo Reserve Park",
                            Type = "Reserve",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 18,
                            AreaSqKm = 5.00m,
                            EstablishedYear = 1937,
                            IsDeleted = false,
                            Name = "Pobiti Kamani Park",
                            Type = "Geological",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 19,
                            AreaSqKm = 110.00m,
                            EstablishedYear = 1976,
                            IsDeleted = false,
                            Name = "Kresna Gorge Park",
                            Type = "Regional",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 20,
                            AreaSqKm = 60.00m,
                            EstablishedYear = 1992,
                            IsDeleted = false,
                            Name = "Veleka River Park",
                            Type = "River",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 21,
                            AreaSqKm = 95.00m,
                            EstablishedYear = 1982,
                            IsDeleted = false,
                            MountainId = 3,
                            Name = "Kalofer Peak Park",
                            Type = "Mountain",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 22,
                            AreaSqKm = 30.00m,
                            EstablishedYear = 1970,
                            IsDeleted = false,
                            MountainId = 3,
                            Name = "Buzludzha Area Park",
                            Type = "Historic",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 23,
                            AreaSqKm = 20.00m,
                            EstablishedYear = 1951,
                            IsDeleted = false,
                            Name = "Kamchia Reserve",
                            Type = "Reserve",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 24,
                            AreaSqKm = 42.00m,
                            EstablishedYear = 1985,
                            IsDeleted = false,
                            MountainId = 3,
                            Name = "Uzana Area",
                            Type = "Regional",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 25,
                            AreaSqKm = 140.00m,
                            EstablishedYear = 1992,
                            IsDeleted = false,
                            Name = "Maleshevo Park",
                            Type = "Nature",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 26,
                            AreaSqKm = 210.00m,
                            EstablishedYear = 1990,
                            IsDeleted = false,
                            Name = "Sakar Mountain Park",
                            Type = "Regional",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 27,
                            AreaSqKm = 18.00m,
                            EstablishedYear = 1960,
                            IsDeleted = false,
                            MountainId = 5,
                            Name = "Cherni Vrah Reserve",
                            Type = "Reserve",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 28,
                            AreaSqKm = 40.00m,
                            EstablishedYear = 1950,
                            IsDeleted = false,
                            Name = "Belogradchik Rocks Park",
                            Type = "Geological",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 29,
                            AreaSqKm = 80.00m,
                            EstablishedYear = 1987,
                            IsDeleted = false,
                            Name = "Shumen Plateau Nature Park",
                            Type = "Nature",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 30,
                            AreaSqKm = 12.00m,
                            EstablishedYear = 1994,
                            IsDeleted = false,
                            Name = "Snezhanka Park",
                            Type = "Recreation",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 31,
                            AreaSqKm = 55.00m,
                            EstablishedYear = 1978,
                            IsDeleted = false,
                            MountainId = 5,
                            Name = "Bistritsa Forest Park",
                            Type = "Forest",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 32,
                            AreaSqKm = 160.00m,
                            EstablishedYear = 1983,
                            IsDeleted = false,
                            MountainId = 1,
                            Name = "Beli Iskar Nature Park",
                            Type = "Nature",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 33,
                            AreaSqKm = 35.00m,
                            EstablishedYear = 1995,
                            IsDeleted = false,
                            Name = "Devol River Park",
                            Type = "River",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 34,
                            AreaSqKm = 25.00m,
                            EstablishedYear = 1989,
                            IsDeleted = false,
                            MountainId = (int?)null,
                            Name = "Gotse Delchev Park",
                            Type = "Regional",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 35,
                            AreaSqKm = 10.00m,
                            EstablishedYear = 1998,
                            IsDeleted = false,
                            MountainId = (int?)null,
                            Name = "Ruse Island Park",
                            Type = "Island",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 36,
                            AreaSqKm = 22.00m,
                            EstablishedYear = 1976,
                            IsDeleted = false,
                            MountainId = (int?)null,
                            Name = "Pleven Meadows Park",
                            Type = "Meadow",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 37,
                            AreaSqKm = 14.00m,
                            EstablishedYear = 1980,
                            IsDeleted = false,
                            MountainId = 3,
                            Name = "Stara Zagora Green Park",
                            Type = "Urban",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 38,
                            AreaSqKm = 65.00m,
                            EstablishedYear = 1950,
                            IsDeleted = false,
                            MountainId = 2,
                            Name = "Bansko Ski Area Park",
                            Type = "Recreation",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 39,
                            AreaSqKm = 95.00m,
                            EstablishedYear = 1990,
                            IsDeleted = false,
                            MountainId = 4,
                            Name = "Smolyan Pines Park",
                            Type = "Forest",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 40,
                            AreaSqKm = 30.00m,
                            EstablishedYear = 2005,
                            IsDeleted = false,
                            Name = "Dobrich Coastal Park",
                            Type = "Coastal",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 41,
                            AreaSqKm = 9.00m,
                            EstablishedYear = 1954,
                            IsDeleted = false,
                            MountainId = 3,
                            Name = "Varna Botanical Park",
                            Type = "Botanical",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 42,
                            AreaSqKm = 28.00m,
                            EstablishedYear = 1965,
                            IsDeleted = false,
                            MountainId = 2,
                            Name = "Plovdiv Hills Park",
                            Type = "Urban",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 43,
                            AreaSqKm = 40.00m,
                            EstablishedYear = 1950,
                            IsDeleted = false,
                            MountainId = 1,
                            Name = "Sofia Urban Park",
                            Type = "Urban",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 44,
                            AreaSqKm = 180.00m,
                            EstablishedYear = 1993,
                            IsDeleted = false,
                            MountainId = 4,
                            Name = "Burgas Wetlands Park",
                            Type = "Wetland",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 45,
                            AreaSqKm = 48.00m,
                            EstablishedYear = 1986,
                            IsDeleted = false,
                            MountainId = 5,
                            Name = "Veliko Tarnovo Hills Park",
                            Type = "Regional",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 46,
                            AreaSqKm = 16.00m,
                            EstablishedYear = 1991,
                            IsDeleted = false,
                            Name = "Cherven Rocks Park",
                            Type = "Geological",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 47,
                            AreaSqKm = 620.00m,
                            EstablishedYear = 1975,
                            IsDeleted = false,
                            Name = "Strandzha Forest Park",
                            Type = "Forest",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 48,
                            AreaSqKm = 80.00m,
                            EstablishedYear = 1982,
                            IsDeleted = false,
                            MountainId = 1,
                            Name = "Iskar Reservoir Park",
                            Type = "Reservoir",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 49,
                            AreaSqKm = 70.00m,
                            EstablishedYear = 1972,
                            IsDeleted = false,
                            MountainId = 2,
                            Name = "Maritsa Riverbank Park",
                            Type = "River",
                            UnescoSite = false
                        },
                        new
                        {
                            ParkId = 50,
                            AreaSqKm = 210.00m,
                            EstablishedYear = 1999,
                            IsDeleted = false,
                            MountainId = 5,
                            Name = "Mesta Valley Park",
                            Type = "Valley",
                            UnescoSite = false
                        });
                });

            modelBuilder.Entity("LocalInformationSystem.Data.Entities.Province", b =>
                {
                    b.Property<int>("ProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProvinceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProvinceId"));

                    b.Property<string>("AdministrativeCenter")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("AreaSqKm")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Population")
                        .HasColumnType("int");

                    b.HasKey("ProvinceId")
                        .HasName("PK__Province__FD0A6FA3FB7A9662");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            ProvinceId = 1,
                            AdministrativeCenter = "Sofia",
                            AreaSqKm = 7000.00m,
                            Name = "Sofia Province",
                            Population = 1200000
                        },
                        new
                        {
                            ProvinceId = 2,
                            AdministrativeCenter = "Plovdiv",
                            AreaSqKm = 5000.00m,
                            Name = "Plovdiv Province",
                            Population = 700000
                        },
                        new
                        {
                            ProvinceId = 3,
                            AdministrativeCenter = "Varna",
                            AreaSqKm = 3800.00m,
                            Name = "Varna Province",
                            Population = 470000
                        },
                        new
                        {
                            ProvinceId = 4,
                            AdministrativeCenter = "Burgas",
                            AreaSqKm = 4100.00m,
                            Name = "Burgas Province",
                            Population = 420000
                        },
                        new
                        {
                            ProvinceId = 5,
                            AdministrativeCenter = "Veliko Tarnovo",
                            AreaSqKm = 4000.00m,
                            Name = "Veliko Tarnovo Province",
                            Population = 260000
                        },
                        new
                        {
                            ProvinceId = 6,
                            AdministrativeCenter = "Blagoevgrad",
                            AreaSqKm = 6800.00m,
                            Name = "Blagoevgrad Province",
                            Population = 320000
                        },
                        new
                        {
                            ProvinceId = 7,
                            AdministrativeCenter = "Ruse",
                            AreaSqKm = 2800.00m,
                            Name = "Ruse Province",
                            Population = 210000
                        },
                        new
                        {
                            ProvinceId = 8,
                            AdministrativeCenter = "Pleven",
                            AreaSqKm = 3600.00m,
                            Name = "Pleven Province",
                            Population = 250000
                        });
                });

            modelBuilder.Entity("LocalInformationSystem.Data.Entities.River", b =>
                {
                    b.Property<int>("RiverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RiverID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RiverId"));

                    b.Property<decimal>("LengthKm")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Outflow")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RiverId")
                        .HasName("PK__Rivers__54DB03CB67C09060");

                    b.ToTable("Rivers");

                    b.HasData(
                        new
                        {
                            RiverId = 1,
                            LengthKm = 368.50m,
                            Name = "Iskar",
                            Outflow = "Danube"
                        },
                        new
                        {
                            RiverId = 2,
                            LengthKm = 480.00m,
                            Name = "Maritsa",
                            Outflow = "Aegean Sea"
                        },
                        new
                        {
                            RiverId = 3,
                            LengthKm = 2850.00m,
                            Name = "Dunav (Danube)",
                            Outflow = "Black Sea"
                        },
                        new
                        {
                            RiverId = 4,
                            LengthKm = 415.00m,
                            Name = "Struma",
                            Outflow = "Aegean Sea"
                        },
                        new
                        {
                            RiverId = 5,
                            LengthKm = 260.00m,
                            Name = "Mesta",
                            Outflow = "Aegean Sea"
                        },
                        new
                        {
                            RiverId = 6,
                            LengthKm = 290.00m,
                            Name = "Arda",
                            Outflow = "Maritsa"
                        },
                        new
                        {
                            RiverId = 7,
                            LengthKm = 314.00m,
                            Name = "Osam",
                            Outflow = "Danube"
                        },
                        new
                        {
                            RiverId = 8,
                            LengthKm = 285.00m,
                            Name = "Yantra",
                            Outflow = "Danube"
                        });
                });

            modelBuilder.Entity("LocalInformationSystem.Data.Entities.City", b =>
                {
                    b.HasOne("LocalInformationSystem.Data.Entities.Province", "Province")
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceId")
                        .IsRequired()
                        .HasConstraintName("FK__Cities__Province__72C60C4A");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("LocalInformationSystem.Data.Entities.Landmark", b =>
                {
                    b.HasOne("LocalInformationSystem.Data.Entities.City", "City")
                        .WithMany("Landmarks")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK__Landmarks__CityI__76969D2E");

                    b.Navigation("City");
                });

            modelBuilder.Entity("LocalInformationSystem.Data.Entities.Park", b =>
                {
                    b.HasOne("LocalInformationSystem.Data.Entities.Mountain", "Mountain")
                        .WithMany("Parks")
                        .HasForeignKey("MountainId")
                        .HasConstraintName("FK__Parks__MountainI__00200768");

                    b.Navigation("Mountain");
                });

            modelBuilder.Entity("LocalInformationSystem.Data.Entities.City", b =>
                {
                    b.Navigation("Landmarks");
                });

            modelBuilder.Entity("LocalInformationSystem.Data.Entities.Mountain", b =>
                {
                    b.Navigation("Parks");
                });

            modelBuilder.Entity("LocalInformationSystem.Data.Entities.Province", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
